In [2]:
#newton's method
import numpy as np
def newton(theta0):
    X=np.array([[1,0,3],[1,1,3],[1,0,1],[1,1,1]])
    y=np.array([[1],[1],[0],[0]])
    lamada=0.07
    I=np.array([[1,0,0],[0,1,0],[0,0,1]])
    def h(x):
        return 1/(1+np.exp(-x@theta0))
    s=np.zeros((4,4))
    np.fill_diagonal(s,[ list(h(X[0])*(1-h(X[0])))[0],list(h(X[1])*(1-h(X[1])))[0],
                        list(h(X[2])*(1-h(X[2])))[0], list(h(X[3])*(1-h(X[3])))[0]] )
    sum1=0
    for i in range(0,4):
        sum1=sum1+(y[i]-h(X[i]))*X[i]    

    Jdot0=-1/4*sum1+lamada/4*theta0.T
    H=1/4*(X.T@s@X)+1/4*lamada*I

    theta1=theta0-np.linalg.inv(H)@Jdot0.T
    return theta1
theta0=np.array([[0,-2,1]]).T
for i in range (5):
    print(newton(theta0))
    theta0=newton(theta0)


[[-3.15199171]
 [-0.40585887]
 [ 1.81504991]]
[[-3.05974654]
 [-0.56975371]
 [ 1.89970566]]
[[-3.07034543]
 [-0.57698163]
 [ 1.91357396]]
[[-3.07041245]
 [-0.57702751]
 [ 1.91369206]]
[[-3.07041245]
 [-0.57702752]
 [ 1.91369207]]
